version: '3.8'

services:
  api:
    image: ghcr.io/amirzenoozi/sentiment-app:${IMAGE_TAG:-latest}
    container_name: dutch_sentiment_api
    ports:
      - "8022:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - TRANSLATION_API_URL=http://translation_service:5000/translate
      - SUPPORTED_TRANSLATION_LANGS=en,it,de
    volumes:
      - ./model:/app/best_model
      - ./quantized_model:/app/quantized_model
    depends_on:
      - mlflow_server
      - translation_service
    networks:
      - sentiment_network
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/ready').read()"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 120s

  translation_service:
    image: libretranslate/libretranslate:latest
    container_name: local_translation_service
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=en,nl,de,it
    networks:
      - sentiment_network
    restart: always

networks:
  sentiment_network:
    driver: bridge